#ifndef TUNGSTEN_REFLECT_GENERATED_PROJECT_DEFINES_HPP
#define TUNGSTEN_REFLECT_GENERATED_PROJECT_DEFINES_HPP

#include "TungstenCore/TungstenCore.hpp"

#define TUNGSTEN_PROJECT_INCLUDE_PATH "@TUNGSTEN_PROJECT_INCLUDE_PATH@"
#define TUNGSTEN_PROJECT_COMPONENT_LIST @TUNGSTEN_PROJECT_COMPONENT_LIST@

#endif