#ifndef TUNGSTEN_RUNTIME_GENERATED_PROJECT_DEFINES_HPP
#define TUNGSTEN_RUNTIME_GENERATED_PROJECT_DEFINES_HPP

#include "TungstenCore.hpp"

#define TUNGSTEN_PROJECT_INCLUDE_PATH "@TUNGSTEN_PROJECT_INCLUDE_PATH@"
#define TUNGSTEN_PROJECT_INIT(x) @TUNGSTEN_PROJECT_INIT@

#endif